// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWB5IDbe1lKf_SZFAKzIQZ7iW_5H0oeI',
    appId: '1:363107472034:web:d06ae6436124a90c57bdfb',
    messagingSenderId: '363107472034',
    projectId: 'casino-9ff89',
    authDomain: 'casino-9ff89.firebaseapp.com',
    storageBucket: 'casino-9ff89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgYBG09B-BYHbHAC0aIc-rIFh73YV-Nw',
    appId: '1:363107472034:android:04b861f84254578557bdfb',
    messagingSenderId: '363107472034',
    projectId: 'casino-9ff89',
    storageBucket: 'casino-9ff89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNqwmif-G5wfcDMDJfqqMXmc5jbmYtm7A',
    appId: '1:363107472034:ios:107065e24351587857bdfb',
    messagingSenderId: '363107472034',
    projectId: 'casino-9ff89',
    storageBucket: 'casino-9ff89.appspot.com',
    iosBundleId: 'com.casino.www.casino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNqwmif-G5wfcDMDJfqqMXmc5jbmYtm7A',
    appId: '1:363107472034:ios:107065e24351587857bdfb',
    messagingSenderId: '363107472034',
    projectId: 'casino-9ff89',
    storageBucket: 'casino-9ff89.appspot.com',
    iosBundleId: 'com.casino.www.casino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUWB5IDbe1lKf_SZFAKzIQZ7iW_5H0oeI',
    appId: '1:363107472034:web:0c5892cb29a87f2757bdfb',
    messagingSenderId: '363107472034',
    projectId: 'casino-9ff89',
    authDomain: 'casino-9ff89.firebaseapp.com',
    storageBucket: 'casino-9ff89.appspot.com',
  );
}
